apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webbook
  namespace: argocd
spec:
  project: app
  source:
    repoURL: https://github.com/albertorodgz/frontend
    targetRevision: HEAD
    path: helm-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  syncPolicy:
    automated:
      prune: false
      selfHeal: false